config/routes.rb
Mingood::Application.routes.draw do
  resources :snippets
  resources :messages
  resources :images
  resources :pages
  devise_for :users
  
  namespace :admin do 
    resources :pages
    resources :users
    resources :messages
    resources :images
    resources :snippets
  end
    
  match "/admin", :controller => "admin/dashboard", :action => :index

  
  root :to => "pages#home"
  
end

app/views/admin/pages/_form.html.erb
<script type="text/javascript">
$(document).ready(function() {
  //comment...easy
  $('#new_page_form input, #new_page_form textarea').bind('blur keyup',function() {
    //comment
    $('#lp-body').html($('#page_body').val());
    $('#lp-body').html($('#lp-body').html());
  });
});
</script>

<div id="new_page_form">
  
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="seo_fields">
    <legend>Required</legend>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title, :size => 60 %>
    </div>

    <div class="field">
      <%= f.label :permalink %><br />
      <%= f.text_field :permalink, :size => 60 %>
    </div>

    <div class="field">
      <%= f.label :link_title %><br />
      <%= f.text_field :link_title, :size => 60 %>
    </div>
    
    <div class="field">
      <%= f.label :sort_order %><br />
      <%= f.text_field :sort_order, :type => "number", :size => 10 %>
    </div>
  </fieldset>
  

  <fieldset class="seo_fields">
    <legend>SEO Fields</legend>
    <div class="field">
      <%= f.label :meta_title %><br />
      <%= f.text_field :meta_title, :size => 88 %>
    </div>

    <div class="field">
      <%= f.label :meta_keywords %><br />
      <%= f.text_field :meta_keywords, :size => 88 %>
    </div>
  
    <div class="field">
      <%= f.label :meta_description %><br />
      <%= f.text_area :meta_description, :rows => 4, :cols => 92 %>
    </div>
  </fieldset>

  
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :rows => 22, :cols => 96 %>
  </div>

  <!-- <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  -->
</div>

<p>Preview:</p>
<div id="live-preview-display" class="lp-block">
  <div id="lp-body"></div>
</div>
<p><em>* It may show different on front end website *</em></p>
<br />

app/views/admin/pages/edit.html.erb
<h1>Editing page</h1>

<%= form_for(@page, :url => { :action => "update" }, :html => { :multipart => true }) do |f| %>
  <%= render 'form', :f => f %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/pages/home.html.erb
<!-- right panel div starts here-->
<%= @home_page.body.html_safe %>
<%= render :partial => "/shared/twitter" %>
<!-- right panel div ends here-->

app/views/admin/pages/index.html.erb
<script type="text/javascript">
  $(document).ready(function() {
      $(function() {
        /* For zebra striping */
        $("table tr:nth-child(odd)").addClass("odd-row");
        /* For cell text alignment */
        $("table td:first-child, table th:first-child").addClass("first");
        /* For removing the last border */
        $("table td:last-child, table th:last-child").addClass("last");
      });
  });
</script>

<% @title ||= "Pages" %>

<table cellspacing="0" >
  <tr>
    <th><%= sort_link @search, :id %></th>
    <th><%= sort_link @search, :sort_order, "Order" %></th>
    <th><%= sort_link @search, :title %></th>
    <th><%= sort_link @search, :permalink %></th>
    <th>Link Title</th>
    <th>Meta Title</th>
    <th>Meta Keywords</th>
    <th width="120px">Meta Description</th>
    <th width="120px"><%= sort_link @search, :updated_at, "Last Update" %></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= link_to page.id, admin_page_path(page) %></td>
    <td><%= page.sort_order %></td>
    <td><%= page.title %></td>
    <td><%= link_to page.permalink, admin_page_path(page) %></td>
    <td><%= page.link_title %></td>
    <td><%= page.meta_title %></td>
    <td><%= page.meta_keywords %></td>
    <td><%= page.meta_description %></td>
    <td><%= time_ago_in_words(page.updated_at) %> ago<br /><span class="info"><%= page.updated_at.to_s(:short) %></span></td>
    <td><%= link_to 'Edit', edit_admin_page_path(page) %></td>
    <td><%= link_to 'Del', admin_page_path(page), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>



<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @pages %>
  </div>
  <%= will_paginate @pages, :container => false %>
</div>

<p>
  Show
  <%= link_to "10", :per_page => 10 %>
  <%= link_to "20", :per_page => 20 %>
  <%= link_to "50", :per_page => 50 %>
  <%= link_to "100", :per_page => 100 %>
</p>


<br />
<p><%= link_to 'New Page', new_admin_page_path %></p>

app/views/admin/pages/new.html.erb
<h1>New page</h1>

<%= form_for(@page, :url => { :action => "create" }, :html => { :multipart => true }) do |f| %>
  <%= render 'form', :f => f %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/pages/show.html.erb
<br clear="both"/>

<% title @page.title %>

<h2><%= @page.title %></h2>

<br clear="both"/>

<%= @page.body.html_safe %>

<br clear="both"/>

<p>
  <%= link_to 'Edit', edit_admin_page_path(@page) %> |
  <%= link_to 'Back', admin_pages_path %>
</p>