config/routes.rb
Mingood::Application.routes.draw do
  resources :snippets
  resources :messages
  resources :images
  resources :pages
  devise_for :users
  
  namespace :admin do 
    resources :pages
    resources :users
    resources :messages
    resources :images
    resources :snippets
  end
    
  match "/admin", :controller => "admin/dashboard", :action => :index

  
  root :to => "pages#home"
  
end

app/models/snippet.rb
class Snippet < Item
  
  def to_param
    permalink.parameterize
  end
  
  
end

app/controllers/admin/snippets_controller.rb
class Admin::SnippetsController < Admin::BaseController

  # GET /snippets
  # GET /snippets.xml
  def index
    @search = Snippet.search(params[:search])
    @snippets = @search.order(:title).paginate(:page => params[:page], :per_page => @per_page)
    @title = "Pages Directory"

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @snippets }
    end
  end

  def home
  end
  
  # GET /snippets/1
  # GET /snippets/1.xml
  def show
    @snippet = Snippet.where(:permalink => params[:permalink]).first if params[:permalink]
    @snippet = Snippet.where(:permalink => params[:id]).first if params[:id]
    # @snippet = Snippet.where(:permalink => params[:id]).first
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @snippet }
    end
  end

  # GET /snippets/new
  # GET /snippets/new.xml
  def new
    @snippet = Snippet.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @snippet }
    end
  end

  # GET /snippets/1/edit
  def edit
    # @snippet = Snippet.find(params[:id])
    @snippet = Snippet.where(:permalink => params[:id]).first
  end

  # POST /snippets
  # POST /snippets.xml
  def create
    @snippet = Snippet.new(params[:snippet])

    respond_to do |format|
      if @snippet.save
        FileUtils.rm_rf "#{Rails.root}/public/pages"
        FileUtils.rm_rf "#{Rails.root}/public/index.html"
        format.html { redirect_to(admin_snippet_path(@snippet), :notice => 'Snippet was successfully created.') }
        format.xml  { render :xml => @snippet, :status => :created, :location => @snippet }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @snippet.errors, :status => :unprocessable_entity }
      end
    end
    
  end

  # PUT /snippets/1
  # PUT /snippets/1.xml
  def update
    # @snippet = Snippet.find(params[:id])
    @snippet = Snippet.where(:permalink => params[:id]).first    

    respond_to do |format|
      if @snippet.update_attributes(params[:snippet])
        FileUtils.rm_rf "#{Rails.root}/public/pages"
        FileUtils.rm_rf "#{Rails.root}/public/index.html"
        format.html { redirect_to(admin_snippet_path(@snippet), :notice => 'Snippet was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @snippet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.xml
  def destroy
    # @snippet = Snippet.find(params[:id])
    @snippet = Snippet.where(:permalink => params[:id]).first
    expire_snippet "/#{@snippet.permalink}"
    expire_snippet "/snippets/#{@snippet.permalink}"
    # expire_snippet :controller => 'snippets', :action => 'show', :id => @snippet.permalink
    # system("rm -rf #{Rails.root}/public/#{@snippet.permalink}")
    # system("rm -rf #{Rails.root}/public/snippets/")
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to(admin_snippets_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/admin/snippets/_form.html.erb
<script type="text/javascript">
$(document).ready(function() {
  //comment...easy
  $('#new_snippet_form input, #new_snippet_form textarea').bind('blur keyup',function() {
    //comment
    $('#lp-body').html($('#snippet_body').val());
    $('#lp-body').html($('#lp-body').html());
  });
});
</script>

<div id="new_snippet_form">
  
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="seo_fields">
    <legend>Required</legend>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title, :size => 60 %>
    </div>

    <div class="field">
      <%= f.label :permalink, "Snippet Code" %><br />
      <%= f.text_field :permalink, :size => 60 %>
    </div>

  </fieldset>


  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :rows => 22, :cols => 96 %>
  </div>

</div>

<p>Snippet Preview:</p>
<div id="live-preview-display" class="lp-block">
  <div id="lp-body"></div>
</div>
<br />

app/views/admin/snippets/edit.html.erb
<h1>Editing snippet</h1>

<%= form_for(@snippet, :url => { :action => "update" }, :html => { :multipart => true }) do |f| %>
  <%= render 'form', :f => f %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/snippets/home.html.erb
<!-- right panel div starts here-->
<%= @home_snippet.body.html_safe %>
<%= render :partial => "/shared/twitter" %>
<!-- right panel div ends here-->

app/views/admin/snippets/index.html.erb
<script type="text/javascript">
  $(document).ready(function() {
      $(function() {
        /* For zebra striping */
        $("table tr:nth-child(odd)").addClass("odd-row");
        /* For cell text alignment */
        $("table td:first-child, table th:first-child").addClass("first");
        /* For removing the last border */
        $("table td:last-child, table th:last-child").addClass("last");
      });
  });
</script>

<% @title ||= "Snippets" %>

<table cellspacing="0" >
  <tr>
    <th>Title</th>
    <th>Code</th>
    <th>Last Update</th>
    <th></th>
    <th></th>
  </tr>

<% @snippets.each do |snippet| %>
  <tr>
    <td><%= link_to snippet.title, admin_snippet_path(snippet) %></td>
    <td><%= link_to snippet.permalink, admin_snippet_path(snippet) %></td>
    <td><%= time_ago_in_words(snippet.updated_at) %> ago | <span class="info"><%= snippet.updated_at.to_s(:short) %></span></td>
    <td><%= link_to 'Edit', edit_admin_snippet_path(snippet) %></td>
    <td><%= link_to 'Del', admin_snippet_path(snippet), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>


<br />
<h3><%= link_to 'New Snippet', new_admin_snippet_path %></h3>
<br />

<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @snippets %>
  </div>
  <%= will_paginate @snippets, :container => false %>
</div>

app/views/admin/snippets/new.html.erb
<h1>New snippet</h1>

<%= form_for(@snippet, :url => { :action => "create" }, :html => { :multipart => true }) do |f| %>
  <%= render 'form', :f => f %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/snippets/show.html.erb
<br clear="both"/>

<% title @snippet.title %>

<h2><%= @snippet.title %></h2>

<br clear="both"/>

<h3>Code:</h3>
<pre><%= @snippet.body %></pre>


<br clear="both"/>

<h3>Preview:</h3>
<%= @snippet.body.html_safe %>

<br clear="both"/>

<p>
  <%= link_to 'Edit', edit_admin_snippet_path(@snippet) %> |
  <%= link_to 'Back', admin_snippets_path %>
</p>