config/routes.rb
Mingood::Application.routes.draw do
  resources :snippets
  resources :messages
  resources :images
  resources :pages
  devise_for :users
  
  namespace :admin do 
    resources :pages
    resources :users
    resources :messages
    resources :images
    resources :snippets
  end
    
  match "/admin", :controller => "admin/dashboard", :action => :index

  
  root :to => "pages#home"
  
end

app/models/image.rb
class Image < ActiveRecord::Base
  
  scope :gallery, where(:gallery => true)
  scope :featured, where(:featured => true)
  scope :published, where(:published => true)
  
  belongs_to :page, :foreign_key => "parent_id"
  
  # has_attached_file :document
  
  has_attached_file :data,
    :styles => {
      :galery => {:geometry => "800x800>", :quality => 92}, 
      :large => {:geometry => "360x360>", :quality => 92}, 
      :medium => {:geometry => "240x240>", :quality => 92}, 
      :small => {:geometry => "120x120>", :quality => 92}, 
      :thumb => {:geometry => "64x64#", :quality => 92},
      :mini => {:geometry => "48x48#", :quality => 92}
    },
    :convert_options => { 
      :galery => '-quality 92',
      :large => '-quality 92',
      :medium => '-quality 92',
      :small => '-quality 92',
      :thumb => '-quality 92',
      :mini => '-quality 92'
    },
    :path => ":rails_root/public/system/:attachment/:id/:style.:extension",
    :url => "/system/:attachment/:id/:style.:extension"
  
  # handling delete of image data
  attr_accessor :delete_data
  before_save { self.data = nil if self.delete_data == '1' }
  
end

app/controllers/admin/images_controller.rb
# -*- encoding : utf-8 -*-
class Admin::ImagesController < Admin::BaseController
  
  # GET /images
  # GET /images.xml
  def index
    @search = Image.search(params[:search])
    @images = @search.order("id DESC").paginate(:page => params[:page], :per_page => @per_page)
    @title = "Images Directory"

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @images }
    end
  end


  # GET /images/1
  # GET /images/1.xml
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @image }
      format.js
    end
  end

  # GET /images/new
  # GET /images/new.xml
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @image }
      format.js
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.xml
  def create
    @image = Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to(admin_image_path(@image), :notice => 'Image was successfully created.') }
        format.xml  { render :xml => @image, :status => :created, :location => @image }
        format.js
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.xml
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to(admin_image_path(@image), :notice => 'Image was successfully updated.') }
        format.xml  { head :ok }
        format.js
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.xml
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to(admin_images_url) }
      format.xml  { head :ok }
      format.js
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.xml
  def index
    @images = Image.published.gallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @images }
    end
  end

  # GET /images/1
  # GET /images/1.xml
  def show
    @image = Image.published.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @image }
      format.js
    end
  end

  # GET /images/new
  # GET /images/new.xml
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @image }
      format.js
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.xml
  def create
    @image = Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to(@image, :notice => 'Image was successfully created.') }
        format.xml  { render :xml => @image, :status => :created, :location => @image }
        format.js
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.xml
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to(@image, :notice => 'Image was successfully updated.') }
        format.xml  { head :ok }
        format.js
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.xml
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to(images_url) }
      format.xml  { head :ok }
      format.js
    end
  end
end

app/views/admin/images/_form.html.erb
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h3>
      <%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:
      </h3>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <fieldset>
    <legend>Image</legend>  
    <p>
      <%= f.label :title, "Image Title" %>
      <%= f.text_field :title, :size => 80 %>
    </p>
    <p>
      <%= f.label :data, "Browse File" %>
      <%= f.file_field :data %>
    </p>
    <p>
      <%= f.check_box :gallery %>
      <%= f.label :gallery, "Show in Image Gallery" %>
    </p>
    <p>
      <%= f.check_box :featured %>
      <%= f.label :featured, "Show in Home Page" %>
    </p>
    <p>
      <%= f.check_box :published %>
      <%= f.label :published, "Visible to Public" %>
    </p>    
    <p>
      <%= f.submit %>
    </p>
  </fieldset>

app/views/admin/images/edit.html.erb
<h1>Editing Image</h1>

<%= form_for(@image, :url => { :action => "create" }, :html => { :multipart => true }) do |f| %>
  <%= render 'form', :f => f %>
<% end %>

<p><%= link_to 'Back', admin_images_path %></p>

app/views/admin/images/index.html.erb
<%= stylesheet_link_tag "table.css" %>

<h2>Listing images <%= link_to 'New Image', new_admin_image_path %></h2>

<table cellspacing="0">
  <tr>
    <th></th>
    <th><%= sort_link @search, :id %></th>
    <th><%= sort_link @search, :title %></th>
    <th><%= sort_link @search, :featured, "Home Page" %></th>
    <th><%= sort_link @search, :gallery, "Gallery" %></th>
    <th><%= sort_link @search, :published, "Visible" %></th>
    <th><%= sort_link @search, :updated_at, "Updated" %></th>
    <th></th>
    <th></th>
  </tr>

<% @images.each do |image| %>
  <tr>
    <td><%= link_to(image_tag(image.data(:small)),admin_image_path(image)) %></td>
    <td><%= image.id %></td>
    <td><%= link_to(image.title,admin_image_path(image))%></td>
    <td><%= image.featured %></td>
    <td><%= image.gallery %></td>
    <td><%= image.published %></td>
    <td><%= image.updated_at.to_s(:short) %></td>
    <td><%= link_to 'Edit', edit_admin_image_path(image) %></td>
    <td><%= link_to 'Destroy', admin_image_path(image), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @images %>
  </div>
  <%= will_paginate @images, :container => false %>
</div>

<p>
  Show
  <%= link_to "10", :per_page => 10 %>
  <%= link_to "20", :per_page => 20 %>
  <%= link_to "50", :per_page => 50 %>
  <%= link_to "100", :per_page => 100 %>
</p>

<h3><%= link_to 'New Image', new_admin_image_path %></h3>

app/views/admin/images/new.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "form" %>
<% end %>

<h1>New Image</h1>

<%= form_for(@image, :url => { :action => "create" }, :html => { :multipart => true }) do |f| %>
  <%= render 'form', :f => f %>
<% end %>

<p><%= link_to 'Back', admin_images_path %></p>

app/views/admin/images/show.html.erb
<h3>
  <%= @image.title %>
</h3>

<br />
<h3>Image Versions:</h3>

<%= image_tag @image.data(:mini) %>
<p><%= @image.data(:mini) %></p>
<br />

<%= image_tag @image.data(:thumb) %>
<p><%= @image.data(:thumb) %></p>
<br />

<%= image_tag @image.data(:small) %>
<p><%= @image.data(:small) %></p>
<br />

<%= image_tag @image.data(:medium) %>
<p><%= @image.data(:medium) %></p>
<br />

<%= image_tag @image.data(:large) %>
<p><%= @image.data(:large) %></p>
<br />

<%= image_tag @image.data(:galery) %>
<p><%= @image.data(:galery) %></p>
<br />

<p>
<%= link_to 'Edit', edit_admin_image_path(@image) %> |
<%= link_to 'Back', admin_images_path %>
</p>